Character = require "./character.coffee"

class Swanson extends Character
	
	buildReplies: ->
		@replies.push "Clear alcohols are for rich women on diets."
		@replies.push "Crying: acceptable at funerals and the Grand Canyon."
		@replies.push "I am going to consume all of this at the same time because I am a free American."
		@replies.push "Under my tutelage, you will grow from boys to men. From men into gladiators. And from gladiators into Swansons."
		@replies.push "I'm a simple man. I like pretty, dark-haired women, and breakfast food."
		@replies.push "Never half-ass two things. Whole-ass one thing."
		@replies.push "Straight down the middle. No hook, no spin, no fuss. Anything more and this becomes figure skating."
		@replies.push "I don’t want to paint with a broad brush here, but every single contractor in the world is a miserable, incompetent thief."
		@replies.push "Fishing relaxes me. It’s like yoga, except I still get to kill something."
		@replies.push "Just give me all the bacon and eggs you have."
		@replies.push "When people get a little too chummy with me I like to call them by the wrong name to let them know I don’t really care about them."
		@replies.push "There’s only one thing I hate more than lying: skim milk. Which is water that’s lying about being milk."
		@replies.push "The government is a greedy piglet that suckles on a taxpayer’s teat until they have sore, chapped nipples."
		@replies.push "I once worked with a guy for three years and never learned his name. Best friend I ever had. We still never talk sometimes."
		@replies.push "When I eat, it is the food that is scared."
		@replies.push "My only official recommendations are US Army-issued mustache trimmers, Morton’s Salt, and the C.R. Lawrence Fein two inch axe-style scraper oscillating knife blade."
		@replies.push "Are you going to tell a man that he can’t fart in his own car?"
		@replies.push "Turkey can never beat cow."
		@replies.push "It’s always a good idea to demonstrate to your coworkers that you are capable of withstanding a tremendous amount of pain."
		@replies.push "There are three acceptable haircuts: high and tight, crew cut, buzz cut."
		@replies.push "Capitalism: God’s way of determining who is smart and who is poor."
		@replies.push "Any dog under fifty pounds is a cat and cats are useless."
		@replies.push "Fish, for sport only, not for meat. Fish meat is practically a vegetable."
		@replies.push "There is only one bad word: taxes."
		@replies.push "History began July 4th, 1776. Anything before that was a mistake."
		@replies.push "Cultivating a manly musk puts opponent on notice."
		@replies.push "Give a man a fish and feed him for a day. Don’t teach a man to fish…and feed yourself. He’s a grown man. And fishing’s not that hard."
		@replies.push "Child labor laws are ruining this country."
		@replies.push "Great job, everyone. The reception will be held in each of our individual houses, alone."
		@replies.push "America: The only country that matters. If you want to experience other 'cultures,'' use an atlas or a ham radio."
		@replies.push "The key to burning an ex-wife effigy is to dip it in paraffin wax and then toss the flaming bottle of isopropyl alcohol from a safe distance. Do not stand too close when you light an ex-wife effigy."
		@replies.push "There are only three ways to motivate people: money, fear, and hunger."
		@replies.push "Shorts over six inches are capri pants, shorts under six inches are European."
		@replies.push "Friends: one to three is sufficient."
		@replies.push "Breakfast food can serve many purposes."
		@replies.push "One rage every three months is permitted. Try not to hurt anyone who doesn’t deserve it."
		@replies.push "Strippers do nothing for me…but I will take a free breakfast buffet anytime, anyplace."
		@replies.push "You had me at meat tornado."
		@replies.push "On second thought i think i will have that third steak."


module.exports = Swanson