Character = require "./character.coffee"

class Veronica extends Character
	
	buildReplies: ->
		@replies.push "The forest will run red with the blood of woodland creatures who doubted little Veronica and will now pay with their furry little lives."
		@replies.push "I saw what was going on in there between you and Fraulein Cheekbones. When you show her around town, keep your Hansels off her Gretels."
		@replies.push "Oh, God, we have unhappy Germans. Nothing good has ever come from that."
		@replies.push "Because I'm good at everything I do. I'm not bragging, because bragging is the one thing I'm not good at. Although, if I wanted to be, I'd be excellent at that, too. As I just proved."
		@replies.push "Do you live here? Do all the cubicle workers have little hobbit holes like this?"
		@replies.push "We believe the multi-language translator will create a furor in Germany, a furor that will sweep across Europe, crushing... no."
		@replies.push "It's just a fun game we're playing--like dress-up, only instead of clothes, we're dressing up the things that are coming out of your mouth."
		@replies.push "I want to burn his diaper and salt the earth beneath it so no new product will ever grow there."
		@replies.push "Well, you are eager and desperate for my approval. And that's two of the three qualities I look for in a partner."
		@replies.push "Then I am ready to leave the monastery and avenge my parents."
		@replies.push "I just buy expensive shoes made from very soft animals."
		@replies.push "I don't take the high road. The high road leads to Pansy Town."
		@replies.push "You're so moral and perfect all the time. Do singing birds and mice dress you and brush your hair in the morning?"
		@replies.push "Has waving your hands ever sold me on anything?"
		@replies.push "Did that MRE touch your boobies? Then shut the hell up."
		@replies.push "In fact, we need to talk about us. And the future of our babies and how they'll be committed."
		@replies.push "I need this relationship to have a future because I need babies."
		@replies.push "I think I might need new breasts. These are covered in sadness."
		@replies.push "I don't hate the Dutch. I love the Dutch. That's why I hold them to a higher standard."
		@replies.push "So this is guilt, huh? In the past, I've always just counteracted this feeling with other emotions, like sugar or drunk."
		@replies.push "Maybe my kindergarten teacher was right. Maybe I am too controlling."
		@replies.push "No, the microphone-attaching elf who lives in my drawer."
		@replies.push "Together, we're like Gandhi. I'm skinny, and you're tan."
		@replies.push "The company loves its money. If they could, they'd go to strip clubs and throw naked women at money."
		@replies.push "The company feels that if we ease up because someone dies, it will only encourage other people to die."
		@replies.push "I heard about Jenkins' death. The company feels terrible about it."
		@replies.push "They're also floating the idea that his being dead may have been a pre-existing condition, and that he may not have been alive when we hired him."
		@replies.push "So am I, and I'll bet Rommel didn't wear a thong underneath his."
		@replies.push "That's the sound of me deflecting the whiny bitching with my happiness shield."
		@replies.push "Great news! You both have a disease."
		@replies.push "We're having a problem with some of those people who live in the cubicles."
		@replies.push "Then when their guard's down, smash them with a phone."
		@replies.push "God, you people are paranoid. No wonder the company has to secretly manipulate you."

module.exports = Veronica